package cmd

import (
	"github.com/mwei2509/strapp/pkg/repo"
	"github.com/spf13/cobra"
)

// repoCreateNextTag represents the app:create command
var repoCreateNextTag = &cobra.Command{
	Use:   "repo:create-next-tag",
	Short: "Let's Boot(strapp) an App",
	Long: `
run from a github directory and create incrementing semver tag:
	
Examples:
  strapp repo:create-next-tag --increment minor
  strapp repo:create-next-tag --increment major
  strapp repo:create-next-tag --increment patch
`,
	Run: func(cmd *cobra.Command, args []string) {
		increment, _ := cmd.Flags().GetString("increment")
		message, _ := cmd.Flags().GetString("message")

		if err := repo.CreateNewTag(increment, message); err != nil {
			log.Fatal(err)
			return
		}
		log.Log("Success!")
	},
}

func init() {
	rootCmd.AddCommand(repoCreateNextTag)
	// flags
	repoCreateNextTag.Flags().StringP("increment", "i", "minor", "increment major, minor (default), or patch")
	repoCreateNextTag.Flags().StringP("message", "m", "auto generated by strapp", "message to include with the new tag")
}
