FROM node:18.12-bullseye-slim

# install
COPY {{.ContextDirectory}}/package*.json /app/
WORKDIR /app
RUN npm ci --omit=optional
COPY {{.ContextDirectory}} /app

# build
RUN npm run build

CMD ["npm", "start"]
